//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\8\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\8\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\8\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\8\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                    __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 5 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\8\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 6 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\8\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Details", "HiCaPhe");


#line default
#line hidden

#line 7 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\8\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("GioHangPartial", "GioHang");


#line default
#line hidden

#line 8 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\8\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("DatHang", "GioHang");


#line default
#line hidden

#line 9 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\8\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Contact", "Home");


#line default
#line hidden

#line 10 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\8\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("DangNhap", "NguoiDung");


#line default
#line hidden

#line 11 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\8\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Login", "Admin");


#line default
#line hidden

#line 12 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\8\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("DangKy", "NguoiDung");


#line default
#line hidden

#line 13 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\8\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
           __o = RenderBody();


#line default
#line hidden

#line 14 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\8\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                                       __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 15 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\8\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                      __o = DateTime.Now.Year;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\nguye\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\7\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\nguye\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\7\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\nguye\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\7\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\nguye\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\7\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                    __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 5 "C:\Users\nguye\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\7\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 6 "C:\Users\nguye\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\7\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Details", "HiCaPhe");


#line default
#line hidden

#line 7 "C:\Users\nguye\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\7\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("GioHangPartial", "GioHang");


#line default
#line hidden

#line 8 "C:\Users\nguye\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\7\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("DatHang", "GioHang");


#line default
#line hidden

#line 9 "C:\Users\nguye\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\7\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Contact", "Home");


#line default
#line hidden

#line 10 "C:\Users\nguye\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\7\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("DangNhap", "NguoiDung");


#line default
#line hidden

#line 11 "C:\Users\nguye\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\7\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Login", "Admin");


#line default
#line hidden

#line 12 "C:\Users\nguye\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\7\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("DangKy", "NguoiDung");


#line default
#line hidden

#line 13 "C:\Users\nguye\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\7\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
           __o = RenderBody();


#line default
#line hidden

#line 14 "C:\Users\nguye\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\7\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                                       __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 15 "C:\Users\nguye\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\7\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                      __o = DateTime.Now.Year;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\5\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\5\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\5\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\5\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                    __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 5 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\5\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 6 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\5\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Contact", "Home");


#line default
#line hidden

#line 7 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\5\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = ;


#line default
#line hidden

#line 8 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\5\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = ;


#line default
#line hidden

#line 9 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\5\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("DangNhap", "NguoiDung");


#line default
#line hidden

#line 10 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\5\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Login", "Admin");


#line default
#line hidden

#line 11 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\5\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = ;


#line default
#line hidden

#line 12 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\5\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
               __o = Html.Action("LayLoaiSP", "HiCaPhe");


#line default
#line hidden

#line 13 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\5\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
           __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                    __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 5 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 6 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("SanPham", "HiCaPhe");


#line default
#line hidden

#line 7 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("SanPham", "HiCaPhe");


#line default
#line hidden

#line 8 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("SanPham", "HiCaPhe");


#line default
#line hidden

#line 9 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("SanPham", "HiCaPhe");


#line default
#line hidden

#line 10 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("SanPham", "HiCaPhe");


#line default
#line hidden

#line 11 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("GioHangPartial", "GioHang");


#line default
#line hidden

#line 12 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
               __o = Html.Action("LayLoaiSP", "HiCaPhe");


#line default
#line hidden

#line 13 "C:\Users\98pha\AppData\Local\Temp\6D901772AE7ADA01A6296AEE540AE81A7243\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
           __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\14\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\14\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\14\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\14\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                    __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 5 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\14\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 6 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\14\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 7 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\14\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 8 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\14\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 9 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\14\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 10 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\14\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 9 "C:\Use11s\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\14\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
               __o = Html.Action("LayLoaiSP", "HiCaPhe");


#line default
#line hidden

#line 10 "C:\Us12s\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\14\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
           __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\nguye\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\13\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\nguye\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\13\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\nguye\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\13\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\nguye\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\13\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                    __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 5 "C:\Users\nguye\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\13\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 6 "C:\Users\nguye\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\13\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 7 "C:\Users\nguye\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\13\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 8 "C:\Users\nguye\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\13\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 9 "C:\Users\nguye\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\13\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 10 "C:\Users\nguye\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\13\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 9 "C:\Use11s\nguye\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\13\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
               __o = Html.Action("LayLoaiSP", "HiCaPhe");


#line default
#line hidden

#line 10 "C:\Us12s\nguye\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\13\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
           __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\11\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\11\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\11\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\11\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
               __o = Html.Action("LayLoaiSP", "HiCaPhe");


#line default
#line hidden

#line 5 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\11\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
           __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\9\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\9\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\9\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\9\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
               __o = Html.Action("LayLoaiSP", "HiCaPhe");


#line default
#line hidden

#line 5 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\9\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
           __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\6\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\6\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\6\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\6\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                    __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 5 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\6\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 6 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\6\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 7 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\6\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 8 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\6\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 9 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\6\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 10 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\6\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 9 "C:\Use11s\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\6\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
               __o = Html.Action("LayLoaiSP", "HiCaPhe");


#line default
#line hidden

#line 10 "C:\Us12s\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\6\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
           __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\4\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\4\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\4\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr";;
 
#line default
#line hidden

#line 4 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\4\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"                __oG"hHtml.Action("LayLoaiSP", "HiCaPhe")UrlgAction(>Indexh,rsHiCaPhe>);

 
<line default
#line hidden

#line 5 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\4\Hicaphe\hicaphe2\Vidden

#line97 "C:\Users\ducng\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\4\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
           __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                         __o = Url.Action("Index", "HiCaPhe");


#line default
#line hidden

#line 5 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
               __o = Html.Action("GioHangPartial", "GioHang");


#line default
#line hidden

#line 6 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                         __o = Url.Action("DangKy", "NguoiDung");


#line default
#line hidden

#line 7 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
                                         __o = Url.Action("DangNhap", "NguoiDung");


#line default
#line hidden

#line 8 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
               __o = Html.Action("LayLoaiSP", "HiCaPhe");


#line default
#line hidden

#line 9 "C:\Users\98pha\AppData\Local\Temp\62FAC74F384349716450F04D765E009910B2\2\Hicaphe\hicaphe2\Views\Shared\_Layout.cshtml"
           __o = RenderBody();


#line default
#line hidden
}
}
}
