    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    namespace hicaphe2.Models
    {
        using System;
        using System.Data.Entity;
        using System.Data.Entity.Infrastructure;
    
        public partial class HiCaPheEntities1 : DbContext
        {
            public HiCaPheEntities1()
                : base("name=HiCaPheEntities1")
            {
            }
    
            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                throw new UnintentionalCodeFirstException();
            }
    
            public virtual DbSet<ADMIN> ADMIN { get; set; }
            public virtual DbSet<CTDATHANG> CTDATHANG { get; set; }
            public virtual DbSet<DONDATHANG> DONDATHANG { get; set; }
            public virtual DbSet<LOAISP> LOAISP { get; set; }
            public virtual DbSet<SANPHAM> SANPHAM { get; set; }
            public virtual DbSet<TAIKHOANKHACHHANG> TAIKHOANKHACHHANG { get; set; }
        }
    }
