//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hicaphe2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTDATHANG = new HashSet<CTDATHANG>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string Kichthuoc { get; set; }
        public string Donvitinh { get; set; }
        public Nullable<decimal> Dongia { get; set; }
        public string Mota { get; set; }
        public string Hinhminhhoa { get; set; }
        public Nullable<int> MaLoaiSP { get; set; }
        public Nullable<int> Soluongban { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDATHANG> CTDATHANG { get; set; }
        public virtual LOAISP LOAISP { get; set; }
    }
}
